[tool.black]
line-length = 80

[tool.mypy]
strict = true
ignore_missing_imports = true
disallow_untyped_decorators = false

[tool.isort]
force_sort_within_sections = true
line_length = 80
profile = "black"

[tool.coverage.run]
branch = true
omit = ["tests/*", "dtx_utils/*"]

[tool.coverage.report]
show_missing = true
skip_empty = true
fail_under = 100
skip_covered = true

[tool.pytest.ini_options]
log_cli = true
log_cli_level = 30
log_cli_format = "%(asctime)s %(levelname)s %(message)s"
log_cli_date_format = "%Y-%m-%d %H:%M:%S"
